server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    routes:
      - id: ticket-service
        uri: lb://TICKET-SERVICE
        predicates:
          - Path=/tickets/**
      - id: vehicle-service
        uri: lb://VEHICLE-SERVICE
        predicates:
          - Path=/vehicles/**
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
          - Path=/users/**
      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
          - Path=/payments/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
